### ISSUE TITLE
  lock main band Work

### ISSUE THREAD

**Issue by ahmadElsharawy** [tpoechtrager/Huawei_Tool#14]
When selecting more than one band the router switches between them  .
I want to put more than one band for better download but I want choose a one main band Work that does not change for a better upload  

i use LTE_1800+2100_UPLOAD_1800.sh but the band change to another band after reboot 
 

router : Huawei b535 - 232   4G+

![Screenshot_2023-08-07-11-56-47-372_com google android apps photos](https://github.com/tpoechtrager/Huawei_Tool/assets/67033609/01b8c850-e1bf-4551-b4cb-882dacf463c5)

**Comment by tpoechtrager** [comment]
Not possible. The UL band setting is not persist. It works merely by chance.
