### ISSUE TITLE
3CA Modes missing

### ISSUE THREAD

**Issue by WonderWhyWilli** [tpoechtrager/Huawei_Tool#5]
Hey,

I got a Huawei B715 and with it you can combine 3 LTE Bands together.

But there are only 2CA mode scripts available at the moment, will there be a script for 3CA in the future?
It is possible to set 3CA with the HManager Android App.

Thank you very much in advance!

Regards,
WonderWhyWilli

**Comment by tpoechtrager** [comment]
Hi,

I don't own a Huawei device at the moment, so it is unlikely new scripts will be added soon.

However, you can create them on your own. For example:

`huawei_band_tool --network-mode 03 --network-band 3FFFFFFF --lte-band +800+1800+2100`

... for 3CA (800 + 1800 + 2100 |  B20, B3 and B1). May not be supported by your router.

**Comment by WonderWhyWilli** [comment]
Thanks for your advice, but the program crashes with this setting.
I can set 3 LTE Bands in the HManager Android App and can read it out with the current band script.
I also get a higher download speed than with just 2 LTE Bands...

**Comment by tpoechtrager** [comment]
Add a screenshot of the crash.

**Comment by WonderWhyWilli** [comment]
![grafik](https://user-images.githubusercontent.com/43491151/66025349-8e2e5680-e4f6-11e9-9a3e-49fb6f16fd27.png)

**Comment by WonderWhyWilli** [comment]
No crash this time, but a wrong band...

**Comment by tpoechtrager** [comment]
Thank you.

Like I already said, I can't do anything at the moment. I do not own a Huawei device anymore. The B715 may use different band masks. I don't know. Or it may just mean the router doesn't support 3CA with that combination.

**Comment by WonderWhyWilli** [comment]
Ok, I wiresharked the whole thing, there is a bug in your tool...
If I send ALL (800D5), the sent xml file says `>524501<` (800D5, but in integer) and not `>800D5<` which would be correct.

1800+2100 would be `>5<`, therefore no error while converting
800 does not work, it will set 900 with the script...

**Comment by tpoechtrager** [comment]
That's a strange coincidence but thanks for reporting. :-)

https://github.com/tpoechtrager/Huawei_Tool/blob/unfinished/src/web.cpp#L958

`%llu` should be `%llx`

**Comment by sprucas** [comment]
Hi Guys,
I know this thread is a little bit stale - but wanted to share some findings. B618s-65d cannot do 3CA

I asked the Huawei team for their product specifications and they replied as below

However, here are some details of B618s-65d may help you finding carrier aggregation band configuration:

Network standard:

− LTE FDD: 4*4MIMO+2CA 582 Mbit/s
− LTE TDD: 4*4MIMO+2CA 426 Mbit/s
− DC-HSPA+: DL 42 Mbit/s, UL 5.76 Mbit/s
− HSPA+: DL 21 Mbit/s (64QAM) / 28 Mbit/s (MIMO), UL 5.76 Mbit/s
− HSPA: DL 14.4 Mbit/s, UL 5.76 Mbit/s
− WCDMA PS: 384 kbit/s
− EDGE: DL 296 kbit/s, UL 236.8 kbit/s
− GPRS: 85.6 kbit/s

LTE Category: Cat 11

Operating Frequency:

LTE: Band 1/3/5/7/8/28/40
Intraband contiguous: CA_1C, CA_3C, CA_5B, CA_7C, CA_8B, CA_40C
Interband: CA_1A3A, CA_3A7A, CA_7A28A
DCHSPA+/HSPA+/HSPA/UMTS:
Band 1/5/8
EDGE/GPRS/GSM:
Band 2/3/5/8
WLAN:
2.4GHz 2.400 GHz～2.474 GHz
5GHz 5.150GHz～5.350GHz&5.470GHz～5.725GHz

You can see the specification says 2CA for LTE FDD and LTE TDD
Another interesting note on the specification is the IntraBand and InterBand Carrier Aggregation options
InterBand is quite limited - only Band1+Band3 or Band3+Band7 or Band7+Band28
IntraBand allows CA on All Bands except B28

At my place I get the best performance using B3 + B40 CA (tested on an Netgear AC800s modem) - but this configuration is not possible on the Huawei (unfortunately)

btw: tpoechtrager's code has been great > but don't know how to code. so I use the scripts here https://github.com/theRealAJR/LTE-Router-Huawei-B618s-22d to login to modem and push net-mode commands to the modem

**Comment by tpoechtrager** [comment]
Should be fixed with https://github.com/tpoechtrager/Huawei_Tool/commit/524c5508df27e59ef9b1ea91063bfcb7200c9512.

New build available @ https://drive.google.com/open?id=0B2hB5md6Sd_vVWlHekl2MDI4NkE. Untested. I don't have a Huawei Router anymore.
