### ISSUE TITLE
 --lte-band <bitmask>

### ISSUE THREAD

**Issue by leemcx** [tpoechtrager/Huawei_Tool#7]
Hi is it possible to connect to more than one band using the bitmask?
For example I'd like to connect to band 20 (800) and band 32 (1500) using something like: 
./huawei_band_tool --network-mode 03 --network-band 3FFFFFFF --lte-band 0000000000080000 0000000080000000

Thank you.

**Comment by tpoechtrager** [comment]
It's for sure possible [but unfortunately I do not know the bitmask of band 32](https://github.com/tpoechtrager/Huawei_Tool/blob/8d5370e4fef135f7c740d5ef4c1bfe00ef938ec9/src/huawei_tools.h#L507). Maybe you can figure it out by looking at the webinterface sources and tell me?

**Comment by leemcx** [comment]
Thank you for the reply. I believe that the two bitmask above are correct for band 20 and band 32 however, I am unsure how to construct the command with the two bitmasks present. 

Band 20: LTE_BAND_800 = 0x80000, (0000000000080000)
Band 32: LTE_BAND_1500 = 0X80000000 (0000000080000000)

Both work independently with --lte-band command but i'm yet to work out how to connect both bands at the same time.

**Comment by tpoechtrager** [comment]
I added band 32. New builds are available here: https://drive.google.com/drive/u/1/folders/1yS_vk-R4azZOm29OLainSpiCsOrU8nfK

`./huawei_band_tool --lte-band-bitmask-from-string 1500+800
80080000`

**Comment by leemcx** [comment]
Thank you very much! - tested and it's working perfectly.
