### ISSUE TITLE
Parameter to set upload band

### ISSUE THREAD

**Issue by pearlxcore** [tpoechtrager/Huawei_Tool#8]
Hi, there is a command in your tool to set network band to increase upload band. Example below is parameter to send request to Huawei API (api/net/net-mode)

`<request>`
`<NetworkMode>03</NetworkMode>`
`<NetworkBand>100200000CE80380</NetworkBand>`
`<LTEBand>1A08A0C00DF</LTEBand>`
`</request>`

I wonder how to set a band as upload band to increase upload speed.

**Comment by tpoechtrager** [comment]
Not possible. Sorry.
